// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFuSPPu-3iSSNrl6KueEvykeAOLrKUntY',
    appId: '1:679388121448:web:55cfcc09bbbb393b372edd',
    messagingSenderId: '679388121448',
    projectId: 'code-assist-pr',
    authDomain: 'code-assist-pr.firebaseapp.com',
    storageBucket: 'code-assist-pr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQsnYuCpTgf2a64kCqyhw7lneEPCQ4pfc',
    appId: '1:679388121448:android:428e7e3f48e5b17e372edd',
    messagingSenderId: '679388121448',
    projectId: 'code-assist-pr',
    storageBucket: 'code-assist-pr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2I9tyGRTvfDQHD-ORGqEw4J2rfAYfUo',
    appId: '1:679388121448:ios:502fb254cbdd5d21372edd',
    messagingSenderId: '679388121448',
    projectId: 'code-assist-pr',
    storageBucket: 'code-assist-pr.appspot.com',
    iosClientId: '679388121448-c6cli8s3nllrt28h383r867n2d1i5n47.apps.googleusercontent.com',
    iosBundleId: 'com.100daysofcode.codeAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2I9tyGRTvfDQHD-ORGqEw4J2rfAYfUo',
    appId: '1:679388121448:ios:502fb254cbdd5d21372edd',
    messagingSenderId: '679388121448',
    projectId: 'code-assist-pr',
    storageBucket: 'code-assist-pr.appspot.com',
    iosClientId: '679388121448-c6cli8s3nllrt28h383r867n2d1i5n47.apps.googleusercontent.com',
    iosBundleId: 'com.100daysofcode.codeAssist',
  );
}
